kumoh42/futsal-server

.eslintrc.js
.gitignore
.prettierrc
README.md
nest-cli.json
package-lock.json
package.json
src/app.controller.spec.ts
src/app.controller.ts
src/app.module.ts
src/app.service.ts
src/main.ts
test/app.e2e-spec.ts
test/jest-e2e.json
tsconfig.build.json
tsconfig.json

nestjs 서버 세팅 및 커밋입니다
https://kumoh42.atlassian.net/browse/KUM-6

nestjs 환경 설정

---

src/entites/xe_reservation.entity.ts
src/entites/xe_reservation_member.entity.ts
src/entites/xe_reservation_pre.entity.ts

+ number 타입인 엔티티에 @Column 메소드에서 length 인자를 붙여줘서 에러가 났었습니다.
+ length 를 삭제하여 오류를 해결했습니다 ! 
+ 꼭 작업하실 때 pull 꼭꼭 하기 !

typeorm number type 인자 삭제

---

.github/workflows/deploy.yml
.gitignore

- deploy.yml에서 사용하지 않은 환경변수들을 제거함.
- gitignore에 lambda 배포 시 생성되는 .serverless 파일들을 추가함.

Kum 51 lambda 환경 세팅

---

src/serverless.ts

fix: Update serverless.ts

---

src/auth/auth.controller.ts
src/auth/jwt/jwt.guard.ts

+ 로그인 응답시 201 -> 200 status code 변경
+ 파라미터가 공백일 시 예외처리 추가
+ 기존 '/refresh' 라우터 400 -> 401 status code 변경 ==> 컨트롤러 전체 코드에 try catch 문을 사용하여 예외시 400코드로 획일화 되어 있던 것을 수정하였음

HOTFIX: changed status code

---

src/main.ts
src/reservation/reservation.service.ts

- 사전 예약 시 조회가 안 되는 오류 확인함
- 정식 예약 테이블 값이 없을 경우 사전 예약 테이블 넘기는 걸로 수정!

사전예약 조회 가능

---

src/slack/slack.service.ts

+ .env 변수에 개행이 존재하여 testing 에 통과하지 못 함
+ service 단에서 맞춰놓은 문자에 개행을 추가함

!HOTFIX:Changed .env && slack service for cicd testing

---

.dockerignore
.github/workflows/deploy.yml
Dockerfile

* Update deploy.yml ---------
Co-authored-by: gimseonjin616 <66009926+gimseonjin@users.noreply.github.com>

Fix: Lambda 함수 용량 크기 조절 (#39)

---

.github/workflows/deploy.yml

!HOTFIX: typo

---

.dockerignore
.github/workflows/deploy.yml
Dockerfile
package-lock.json
package.json
serverless.yml
src/serverless.ts

* Fix: AWS Lambda 환경 변수 설정 오류 수정
* Fix: deploy.yml 실행 버그 수정

Fix: Lambda 버그 수정 (#44)

---

dklfjkl
src/auth/auth.controller.ts
src/auth/auth.service.ts
src/common/decorators/user.decorator.ts
src/common/dto/inquiry-message.dto.ts
src/common/dto/reservation/month-reservation-delete.dto.ts
src/common/dto/reservation/one-reservation-delete.dto.ts
src/reservation/reservation-setting.service.ts
src/reservation/reservation-transaction.ts
src/reservation/reservation.controller.ts
src/reservation/reservation.module.ts
src/reservation/reservation.service.ts
src/serverless.ts
src/slack/slack.controller.ts

+ 기존 삭제 요청 바디의 time type을 array로 변경했습니다.
+ 기타 불필요한 코드를 삭제했습니다.

Feat: 삭제 변경

---

src/slack/slack.service.ts

+ 슬랙 메세지 내용이 개행이 삽입되지 않았습니다.
+ 기존 .env 변수를 변경하여 해결했습니다.

HOTFIX: SLACK ENV VARIABLE CHANGED

---

src/reservation/time/reservation-time.transaction.repository.ts

- 리팩토링 했던 코드들 중에 오류나는 부분들 수정했습니다!
- 사전예약 설정, 사전예약 삭제

KUM-117 리팩토링

---

src/common/dto/members/members.dto.ts
src/common/get-reservation.pipe.ts
src/members/members.controller.ts
src/members/members.module.ts
src/members/members.service.ts
src/pipe/parse-int.pipe.ts
src/reservation/official-reservation/official-reservation.transaction.repository.ts
src/reservation/pre-reservation/pre-reservation.transaction.repository.ts
src/reservation/reservation.controller.ts
src/reservation/reservation.module.ts
src/reservation/reservation.service.ts
src/reservation/time/reservation-time.service.ts
src/reservation/time/reservation-time.transaction.repository.ts

+ 정현님이랑 api 통신을 진행하고, 코드를 수정하는 작업을 거쳤습니다.
+ 서버 코드에서 바꿀 거는 별로 없었습니다.

Kum 131 사용자승인및수정

---

src/reservation/official-reservation/official-reservation.transaction.repository.ts
src/reservation/time/reservation-time.service.ts

- 예약이 삭제되면 srl에 0이 들어감 null이 들어가는 것이 아님!
- 예약 내역을 조회할 때 srl 값이 0이면 null로 바꿔줌
- 예약 값을 지울 떄 srl 값을 null이 아닌 0으로 바꿔줌

fix: delete 시 안 보이는 버그 수정

---

.github/workflows/dev.yml
.gitignore
dev.Dockerfile

[develop을 위한 서버 구축]
- dev.yml : 
- 브랜치 dev에 push할 때 ec2 (futsal-server-develop)에 배포되도록 설정
- dev를 위한 환경 변수 새로 추가함
- Actions 실행할 때마다 Github Actions IP를 추가하고 삭제하여 SSH 접근 제어 강화했습니다!!
- dev.Dockerfile: 기존 Dockerfile은 lambda 이미지라 새로운 Dockerfile 추가

1107 : server for develop

---

src/reservation/reservation-scheduler.ts

슬롯 빌더 : 30분마다
정식 예약 오픈 : 1시간마다 
일단 급한대로 이렇게 설정했습니다

Test: change cronjob

---

src/reservation/official-reservation/official-reservation.transaction.repository.ts

+ 모든 일의 원흉,,,, Inject 데코레이터가 잘못되었던 코드를 수정하였습니다.
+ 사실 이거 하나 때문에 안 넘어가졌던 것 같은데 우연찮케 찾아서 다행입니다.
ㅠㅠ

HOTFIX: fixed InjectDecorator name - Reservation Pre Entity

---

src/reservation/official-reservation/official-reservation.service.ts
src/reservation/official-reservation/official-reservation.transaction.repository.ts
src/reservation/pre-reservation/pre-reservation.service.ts
src/reservation/pre-reservation/pre-reservation.transaction.repository.ts

+ 우선예약 -> 정식예약으로 레코드 move 및 config 수정, 명월 우선예약 레코드 생성하였습니다.

Fix: switch Pre to Main Reservaion table

---

src/reservation/reservation-scheduler.ts

우선예약 시작시 config table key값이 변경되지 않아 코드를 수정했습니다.

Fix: changed function argument

---

src/reservation/reservation.controller.ts

- 예약 현황 조회에서 사전 예약일 때는 조회가 안 되는 것 확인함
- 프론트와 협의 후, 프론트 측에서 현재 예약 상황 알려주면 그에 맞는 예약 현황을 보여주기로 함

feat: add pre-reservation searching

---

src/common/dto/user/make-user.dto.ts
src/entites/xe_reservation_member.entity.ts
src/reservation/reservation.controller.ts
src/user/user.controller.ts
src/user/user.module.ts
src/user/user.service.ts

+ DB 컴럼 추가에 기인하여 XE_RESERVATION_MEMBER.entity를 수정했습니다.
+ 현재 regdate가 timestamp로 안 찍히는 이슈가 있는데 DB쪽에서 해결해야 할 것 같습니다.
+ http request body를 이용하기 위해 dto를 작성했습니다.
+ 코드 수정을 위해 추후에 있을 작업에 사용될 함수를 주석으로 달아놨습니다 ~

Feat: Changed Entity && server logic

---

src/common/dto/user/make-user.dto.ts
src/user/user.service.ts

1. user.service.ts에서 비밀번호 해시 알고리즘 추가 (bcrypt 모듈 사용)
2. make-user.dto 유효성 검사 데코레이터 추가 , 에러 시 메세지 출력하도록 설정

Fix: changed password hassing && validation

---

src/reservation/official-reservation/official-reservation.transaction.repository.ts

+ 정식예약 이전시 불필요한 코드 삭제 및 메소드명을 변경했습니다.
자세한 내용
https://www.notion.so/kumoh42/079cf86d0c2c453eb80fd050f3410f76?pvs=4

HOTIX: change reservation repository

---

src/reservation/time/reservation-time.service.ts

Dev: merge to main

---

src/common/dto/user/make-user.dto.ts
src/user/user.service.ts

1. 회원 정보 수정 시 이미 존재하는 학번일 시 403 에러 출력하도록 하였습니다. 본인 학번을 그대로 유지시킬 경우에는 정상적으로 수정되도록 하였습니다.  
2. 회원가입 때 전화번호 하이픈 미 입력시 에러 발생시키도록 설정하였습니다.

Fix: duplication sNumber&& phoneNumber form
